//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long ID { get; set; }
        public string Full_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Email_Address { get; set; }
        public string Phone_Number { get; set; }
        public string Home_Address { get; set; }
        public Nullable<System.DateTime> Date_Of_Appo { get; set; }
        public Nullable<int> Tests_IDs { get; set; }
        public Nullable<int> Billing_ID { get; set; }
        public string Status { get; set; }
    
        public virtual Billing Billing { get; set; }
        public virtual Test Test { get; set; }
    }
}
